dist: bionic
language: ruby
cache:
  directories:
  - vendor/bundle
services:
  - postgresql
addons:
  postgresql: 10
rvm:
- 2.6.5
- 2.5.7
- 2.4.9
- 2.3.8
env:
- REDMINE_VERSION=4.0.5
- REDMINE_VERSION=3.4.12
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
branches:
  except:
  - debian
before_install:
- gem update --system
- gem install bundler -v '~> 1.0'
- bundle --version
- sudo apt-get install -yq chromium-browser chromium-chromedriver
- export PATH=$PATH:/usr/lib/chromium-browser/
- which chromedriver
- chromedriver --version
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3 --without development
- BUNDLE_OPTS="--without development" ./redmine update
script:
- bundle exec rake spec
