dist: bionic
language: ruby
cache:
  directories: [.cache, vendor]
services:
  - postgresql
rvm:
  - 2.6.5
env:
  global:
  - BROWSER=chromium
  matrix:
  - REDMINE_VERSION=4.1.0
  - REDMINE_VERSION=master
matrix:
  allow_failures:
    - env: REDMINE_VERSION=master
branches:
  except:
    - debian
before_install:
  - nvm install 10
  - sudo apt-get -qy install chromium-browser chromium-chromedriver
  - node --version
  - npm --version
  - bundle --version
  - chromedriver --version
install:
  - export BUNDLE_GEMFILE=""
  - export BUNDLE_PATH="$(pwd)/vendor/bundle"
  - gem install bundler -v '~> 2.0'
  - bundle install --jobs=3 --retry=3
  - npm ci --cache .cache/npm
  - BUNDLE_OPTS="--without development" ./redmine update
script:
  - npm run build
  - bundle exec rspec spec/plugin
  - bundle exec rspec spec/browser
